<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTYiidhc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTYiidhc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTYiidhc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTYiidhc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTYiidhc\App_KernelDevDebugContainer([
    'container.build_hash' => 'TYiidhc',
    'container.build_id' => 'b0035eb2',
    'container.build_time' => 1662737946,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTYiidhc');
